name: aws_iot
description: AWS IoT API client for Dart
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any

  logger: any

  json_annotation: any

  validators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: any
  build_runner: any
  json_serializable: ^3.2.0
  recase: 2.0.1

flutter:
